### ISSUE TITLE
($array) must be of type array, null given

### ISSUE THREAD

**Issue by pbchase** [ctsit/hide_choice_by_event#7]
In the REDCap Community, Liz Moyer reports:

> [liz.moyer](https://redcap.vumc.org/community/profile.php?id=222) asked • 9 minutes ago (2024-10-02 13:08)
> Hide Choice By Event - v1.0.1 - Issues with PHP 8
> [@philip.chase](https://redcap.vumc.org/community/profile.php?id=426) since we upgraded to PHP 8, we are seeing issues with this module when used on participants surveys. the error throws on the close survey page.
> 
> The 'hide_choice_by_event' module threw the following exception when calling the hook method 'hook_every_page_top':
> 
> TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/redcap/modules/hide_choice_by_event_v1.0.1/ExternalModule.php:31
> Stack trace:
> #0 /var/www/html/redcap/modules/hide_choice_by_event_v1.0.1/ExternalModule.php(31): array_keys()
> #1 /var/www/html/redcap/redcap_v14.4.1/ExternalModules/classes/ExternalModules.php(3189): HideChoiceByEvent\ExternalModule\ExternalModule->hook_every_page_top()
> #2 /var/www/html/redcap/redcap_v14.4.1/ExternalModules/classes/ExternalModules.php(3356): ExternalModules\ExternalModules::startHook()
> #3 /var/www/html/redcap/redcap_v14.4.1/ExternalModules/classes/ExternalModules.php(3389): ExternalModules\ExternalModules::ExternalModules\{closure}()
> #4 /var/www/html/redcap/redcap_v14.4.1/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook()
> #5 /var/www/html/redcap/redcap_v14.4.1/Classes/HtmlPage.php(151): Hooks::call()
> #6 /var/www/html/redcap/redcap_v14.4.1/Classes/Survey.php(3898): HtmlPage->PrintHeader()
> #7 /var/www/html/redcap/redcap_v14.4.1/Surveys/index.php(155): Survey::exitSurvey()
> #8 /var/www/html/redcap/surveys/index.php(9): include('...')
> #9 {main}
> 
> We see this in our production instance running 14.4.1 and staging instance running 14.6.0

This looks like another PHP8 bug

**Comment by pbchase** [comment]
Addressed by #8
